.\" see groff_man for syntax.
.TH amalgam.h 3 "2025" "Amalgam Manual pages" "Library Calls"
.SH NAME
amalgam.h \-\- Main header file for the amalgam library.
.SH LIBRARY
libamalgam configure error handling with respect to build mode
.br
\fB(libamalgam -lamalgam)\fP
.SH SYNOPSIS
.SY
.PP
.BI #include\ <amalgam.h>
.br
Includes everything in the library through a single header file.
.PP
Individual header files for the modules.
.PP
.BI #include\ <labuildmode.h>
.br
Lets you configure build modes compiled time that can be identified
.br
run time. Stand alone module. 
.PP
.BI #include\ <laprograminfo.h>
.br
Lets you define the reassuring error message the end\-user sees,
.br
should a
runtime error happen in a "\fBLA_REL\fP" build.
.PP
.BI #include\ <laassert.h>
.br
An assert with configurable behavior with respect to build mode.
.PP
.BI #include\ <lafailfast.h>
.br
A failfast error strategy with configurable behavior with respect
.br
to build mode.
.PP
.BI #include\ <lahappypath.h>
.br
A module for errorchecking with configurable behavior with respect
.br
to build mode.
.PP
.BI #include\ <laexception.h>
.br
A module for exception handling that is open for extension.
.PP
.BI #include\ <lasyserr.h>
.br
A module for returning OS specific constant for that \fBerrno\fP
.YS
.\" todo, write in the interface here.
.SH DESCRIPTION
.PP
\fBAmalgam\fP is a library that provides error handling strategies and
.br
parsing of compile time feature request macros to define the
.br
current
build mode run\-time, making it easy to configure the
.br
behavior of the error handling strategies (error messaging),
.br
letting them behave in a uniform fashion with respect to build
.br
mode. 
.PP
This caters for a unified behavior of different error handling
.br
strategies.
.PP
Therefore \fBamalgam\fP provides a productive addition where it is easy
.br
to configure the error handling for development ", testing and
.br
production for different kind of error handling strategies. 
.PP
The library is meant to let you keep your \fBlaassert\fPions active in
.br
releases, but printing a general user\-friendly error message..
.PP
If you don't specify one of the \fBLA_REL\fP, \fBLA_DEV\fP or \fBLA_DBG\fP feature
.br
requst macros on the compiler command line, the library will
.br
default to \fBLA_DEV\fP giving a "normal" behavior with regards to error
.br
messages.
.SH ENVIRONMENT
The library as such is meant to work first and foremost on Linux
.br
with the
.BR gcc(1)
toolchain and
.BR gdb(1)
which is necessay for the
.br
stack traces. 
.SH SEE ALSO
.BI amalgam(7)
.BI laassert.h(3)
.BI lahappypath.h(3)
.BI lafailfast.h(3)
.br
.BI labuildmode.h(3)
.BI laprograminfo.h(3)
.BI laexception.h(3)
.BI lasyserr.h(3)
.SH AUTHORS AND SOURCES
Mark J.Rochkind Advanced Unix Programming 2nd edition.
.br
David R. Hanson "C Interfaces and Applications"
.br
Brian W. Kernighan and Robert Pike "The Practice of Programming."
.br
Andrew G. Morgan Source code for making executable libraries.
.SH COPYRIGHT
Mark J.Rochkind April 2004-2025
.br
David R. Hanson 1996-2025
.br
Brian W. Kernighan and Robert Pike 1999-2025
.br
Andrew G. Morgan <morgan@kernel.org> 2021-205
.br
Tommy Bollman 2025 Mit License.

.\" vim: nospell
