.\" see groff_man for syntax.
.TH la_programinfo.h 3  "2025" "libamalgam" "Library Functions Manual"
.SH NAME
la_programinfo.h 
.SH LIBRARY
Configurable error handling stragegies with respect to build mode.
.br
\fB(libamalgam -lamalgam)\fP
.SH SYNOPSIS
.BI #include\ <amalgam.h>
.br
or
.br
.BI #include\ <la_programinfo.h>
.SH DESCRIPTION
\fBla_programinfo.h\fP \-\- interface for setting program\-info like program
.br
\-name,
program\-version and the general error message to use in
.br
release\-mode (
.BR LA_REL
)
when something fatal happens run\-time.
.SS List of functions
.nh
.ad l
.TS
;
lb lbx
l l.
Function    Description
_
\fBla_freegeneralerrormsg(3)\fP	T{
free release build error message upon exit
T}
\fBla_freeprogname\fP(3)	T{
free program name upon exit
T}
\fBla_generalerrormsg\fP(3)	T{
return release build error message run\-time
T}
\fBla_progname\fP(3)	T{
return the program name at run\-time
T}
\fBla_progversion\fP(3)	T{
return the program version at run\-time
T}
\fBla_setgeneralerrormsg\fP(3)	T{
set release build error message before use
T}
\fBla_setprogname\fP(3)	T{
set program name before use
T}
\fBla_setprogversion\fP(3)	T{
set program version before use
T}
.TE
.ad
.hy
.SH SEE ALSO
amalgam(7), amalgam.h(3), la_buildmode.h(3) 
.SH AUTHOR
Idea by Rob Pike and B.W. Kernighan in "Practice of Programming".
.\" TODO: really work out the rouitines into syserr.h, so everything is there.
.\" vim: nospell
